### ISSUE TITLE
Hide "coinbase" from Rich list

### ISSUE THREAD

**Issue by minkcrypto-zz** [uaktags/explorer#41]
https://explorer.cpuchain.org/address/coinbase

**Comment by uaktags** [comment]
I've personally never seen this occur. Interesting.

**Comment by uaktags** [comment]
So a few things...

Coinbase should never be in your richlist, nor is it in your example, and you url is for the address itself to just show its balance and transactions. So the link and the richlist phrase are not exactly an accurate representation.
Coinbase should never be in your richlist because cb should never have a positive balance. lib/database.js shows in the update_address function that balance is always 0 and sent is the only thing ever updated.
Is your question instead directed to remove coinbase from being a searchable address? That definitely seems like a UX decision that I can get behind. Otherwise, I'm not seeing the problem.

**Comment by uaktags** [comment]
Closing for now, unanswered questions. Reopen if still an issue.
